apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  destination:
    namespace: logs
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://fluent.github.io/helm-charts'
    targetRevision: 0.19.20
    chart: fluent-bit
    helm:
      values: |
        config:
          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Host elasticsearch-master
                Logstash_Format On
                Retry_Limit False
                net.keepalive Off
                Replace_Dots   On
                Trace_Error    On
  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
